# This workflow publishes a new version to the Github Registry.
#
# @author Armin Schnabel
# @version 1.0.0
# @since 1.0.5
name: Gradle Publish

  on:
    push:
      tags:
        - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Create local.properties with a repository token
      run: |
        # Use the repository's automatically set up token to pushlish to the registry
        echo "github.user=cyface-de" > local.properties
        echo "github.token=${{ secrets.GITHUB_TOKEN }}" >> local.properties
    - name: Publish with Gradle
      run: ./gradlew publish
